"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import LanguageSwitcher from "../../../components/LanguageSwitcher";
import ThemeSwitcher from "../../../components/ThemeSwitcher";
import { useLanguage } from "../../../components/LanguageProvider";

const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://172.18.228.12:8080";
type Requirement = { id: number; riceType: string; quantityKg: number; frequency: string };

export default function MillRequirementsPage() {
  const router = useRouter(); const { language } = useLanguage(); const [requirements, setRequirements] = useState<Requirement[]>([]); const [prices, setPrices] = useState<Record<number, string>>({}); const [error, setError] = useState(""); const [saving, setSaving] = useState<number | null>(null); const si = language === "si";
  const text = si ? { title: "ව්‍යාපාර සහල් අවශ්‍යතා", back: "මෝල් පුවරුව", price: "ඔබේ මිල / කිලෝග්‍රෑම්", offer: "මිල ගණන ඉදිරිපත් කරන්න", saving: "ඉදිරිපත් කරමින්...", empty: "සක්‍රීය අවශ්‍යතා නොමැත.", error: "අවශ්‍යතා ලබාගැනීමට නොහැකි විය." } : { title: "Business Rice Requirements", back: "Mill Dashboard", price: "Your price per kilogram", offer: "Submit Offer", saving: "Submitting...", empty: "No active requirements.", error: "Unable to load requirements." };
  const headers = () => { const token = localStorage.getItem("vee-market-token") || localStorage.getItem("token"); return token ? { Authorization: `Bearer ${token}`, Accept: "application/json", "Content-Type": "application/json" } : null; };
  async function load() { const requestHeaders = headers(); if (!requestHeaders) { router.replace("/login"); return; } try { const response = await fetch(`${API_URL}/api/mill/requirements`, { headers: requestHeaders, cache: "no-store" }); if (!response.ok) throw new Error(text.error); setRequirements(await response.json()); } catch (cause) { setError(cause instanceof Error ? cause.message : text.error); } }
  useEffect(() => { load(); }, [language]);
  async function submit(event: FormEvent<HTMLFormElement>, requirementId: number) { event.preventDefault(); const requestHeaders = headers(); if (!requestHeaders) return; try { setSaving(requirementId); const response = await fetch(`${API_URL}/api/mill/requirements/${requirementId}/offers`, { method: "POST", headers: requestHeaders, body: JSON.stringify({ pricePerKg: Number(prices[requirementId]) }) }); if (!response.ok) throw new Error((await response.json().catch(() => null))?.message || text.error); setPrices((current) => ({ ...current, [requirementId]: "" })); } catch (cause) { setError(cause instanceof Error ? cause.message : text.error); } finally { setSaving(null); } }
  return <main className="min-h-screen bg-slate-50 text-slate-900 dark:bg-slate-950 dark:text-white"><header className="border-b border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><div className="mx-auto flex h-20 max-w-6xl items-center justify-between px-4 sm:px-6"><Link href="/dashboard/mill" className="font-bold text-emerald-700 dark:text-emerald-400">Vee Market</Link><div className="flex gap-2"><LanguageSwitcher /><ThemeSwitcher /></div></div></header><div className="mx-auto max-w-6xl px-4 py-10 sm:px-6"><Link href="/dashboard/mill" className="text-sm font-semibold text-emerald-700 hover:underline dark:text-emerald-400">← {text.back}</Link><h1 className="mt-6 text-3xl font-bold">{text.title}</h1>{error && <p className="mt-5 rounded-xl bg-red-50 p-4 text-red-700 dark:bg-red-950/30 dark:text-red-300">{error}</p>}{requirements.length === 0 ? <div className="mt-8 rounded-3xl border border-dashed border-slate-300 bg-white p-10 text-center dark:border-slate-700 dark:bg-slate-900">{text.empty}</div> : <div className="mt-8 grid gap-5 md:grid-cols-2">{requirements.map((requirement) => <article key={requirement.id} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="text-xl font-bold">{requirement.riceType}</h2><p className="mt-2 text-sm text-slate-500 dark:text-slate-400">{requirement.quantityKg} kg · {requirement.frequency}</p><form onSubmit={(event) => submit(event, requirement.id)} className="mt-6 border-t border-slate-200 pt-5 dark:border-slate-800"><label className="text-sm font-semibold">{text.price}<input required min="0.01" step="0.01" type="number" value={prices[requirement.id] || ""} onChange={(event) => setPrices((current) => ({ ...current, [requirement.id]: event.target.value }))} className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 font-normal dark:border-slate-700 dark:bg-slate-950" /></label><button disabled={saving === requirement.id} className="mt-3 w-full rounded-xl bg-emerald-600 px-4 py-3 font-bold text-white hover:bg-emerald-700 disabled:opacity-60">{saving === requirement.id ? text.saving : text.offer}</button></form></article>)}</div>}</div></main>;
}
