spring.application.name=vee-market-api

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/vee_market}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true

# Server
server.port=8080
