spring.application.name=vee-market-api

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/vee_market
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true

# Server
server.port=8080